### ISSUE TITLE
Oшибка при запуске: python3 setup.py develop

### ISSUE THREAD

**Issue by senitskiy** [tonlabs/TestSuite4#3]
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    with open(os.path.join(HERE, 'README_PYPI.md')) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dima/TestSuite4-1/README_PYPI.md'

Может должно быть просто README.md или есть дополнительный файлик README_PYPI.md?

**Comment by buktop24** [comment]
Здравствуйте, Дмитрий! 
> Может должно быть просто README.md или есть дополнительный файлик README_PYPI.md?

Спасибо за сообщение! Попробуйте скопировать `README.md` или создать пустой `README_PYPI.md`. Это должно помочь.
Мы обязательно исправим эту проблему в следующем апдейте

**Comment by buktop24** [comment]
@senitskiy Дмитрий, выложил отсутствующий файл. Пожалуйста проверьте, что всё теперь собирается.

**Comment by senitskiy** [comment]
Отлично! setup.py отрабатывает без ошибок.

**Comment by senitskiy** [comment]
.
